image: mirisbowring/texlive_ctan_full:2019

stages:
  - deploy

build:
  stage: deploy
  script:
    - mkdir -p ./public/
    - make pdf -j
    - find . -name '*.pdf' | xargs -I% mv % ./public/
  artifacts:
    paths:
    - public
